server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3308/identity_service?allowPublicKeyRetrieval=true&useSSL=false"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

